version: "3"
volumes: 
  node_modules:
  
services:
  bash:
      image: dbsites/db-dependencies
      container_name: db-dependencies
      ports:
        - 8080:8080
      volumes:
        - ./:/usr/src/app
        - node_modules:/usr/src/app/node_modules