# command to run:
# docker-compose -f docker-comp-test.yml up

# This will start db-dependencies & postgres db container with it's associated data volumes container
# and run 'npm run test'

version: "3"
services:

  test:
    image: dbsites/db-dependencies
    container_name: "db-test"
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    depends_on:
      - postgres-db-test
    command: npm run test
    
  postgres-db-test:
    image: dbsites/db-postgres
    container_name: db-test-database
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=dbadmin
      - POSTGRES_DB=dbdb
    volumes:
      - test-db-volume:/var/lib/postgresql/data
    

# shared volumes for development
volumes:
  test-db-volume:
  node_modules: