

const testQuestions = {
    TEST_FOR:null,
    VERY_STRONG: {
        '1':'no',
        '2':'no',
        '3':'yes',
        '3a':'no',
        '4':'yes',
        '5':'no',
        '6':'yes',
        '7':'yes',
        '8':'yes',
        '9':'yes',
        '9a':'yes',
        '9b':'no',
        '9c':'yes',
        '9d':'yes',
        '10':'no',
        '10a':'yes',
        '10b':'yes',
        '11':'no',
        '12':'no',
        '13':'yes',
        '14':'yes',
        '15':'no',
        '16':'yes',
        '17':'no',
        '18':'yes',
        '19':'no',
        '20':'no'
    },
    STRONG:{
        '1':'no',
        '2':'no',
        '3':'yes',
        '3a':'no',
        '4':'yes',
        '5':'no',
        '6':'yes',
        '7':'yes',
        '8':'yes',
        '9':'yes',
        '9a':'yes',
        '9b':'no',
        '9c':'yes',
        '9d':'yes',
        '10':'no',
        '10a':'yes',
        '10b':'yes',
        '11':'yes',
        '12':'yes',
        '13':'yes',
        '14':'yes',
        '15':'yes',
        '16':'yes',
        '17':'yes',
        '18':'yes',
        '19':'no',
        '20':'no'
    },
    MODERATE:{
        '1':'no',
        '2':'no',
        '3':'yes',
        '3a':'no',
        '4':'yes',
        '5':'no',
        '6':'yes',
        '7':'yes',
        '8':'yes',
        '9':'yes',
        '9a':'yes',
        '9b':'no',
        '9c':'yes',
        '9d':'yes',
        '10':'no',
        '10a':'yes',
        '10b':'yes',
        '11':'yes',
        '12':'yes',
        '13':'yes',
        '14':'yes',
        '15':'yes',
        '16':'yes',
        '17':'yes',
        '18':'yes',
        '19':'yes',
        '20':'yes'
    },
    WEAK:{
        '1':'yes',
        '2':'yes',
        '3':'yes',
        '3a':'no',
        '4':'no',
        '5':'yes',
        '6':'no',
        '7':'no',
        '8':'no',
        '9':'no',
        // '9a':'yes',
        // '9b':'no',
        // '9c':'yes',
        // '9d':'yes',
        '10':'yes',
        // '10a':'yes',
        // '10b':'yes',
        '11':'yes',
        '12':'yes',
        '13':'no',
        '14':'no',
        '15':'no',
        '16':'no',
        '17':'no',
        '18':'yes',
        '19':'no',
        '20':'no'
    },
    NO_EVIDENCE:{
        '1':'yes',
        '2':'yes',
        '3':'yes',
        '3a':'no',
        '4':'no',
        '5':'yes',
        '6':'no',
        '7':'no',
        '8':'no',
        '9':'no',
        // '9a':'yes',
        // '9b':'no',
        // '9c':'yes',
        // '9d':'yes',
        '10':'yes',
        // '10a':'yes',
        // '10b':'yes',
        '11':'yes',
        '12':'yes',
        '13':'no',
        '14':'no',
        '15':'no',
        '16':'no',
        '17':'no',
        '18':'yes',
        '19':'yes',
        '20':'yes'
    }
};

export default testQuestions;